"""crear tablas iniciales

Revision ID: 685718307080
Revises: 
Create Date: 2026-02-04 14:34:42.413769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '685718307080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('limite_inferior', sa.Float(), nullable=True),
    sa.Column('limite_superior', sa.Float(), nullable=True),
    sa.Column('valor_critico_bajo', sa.Float(), nullable=True),
    sa.Column('valor_critico_alto', sa.Float(), nullable=True),
    sa.Column('formula_calculo', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('inventario_reactivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identificacion', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('muestras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_unico', sa.String(length=50), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_recepcion', sa.DateTime(), nullable=True),
    sa.Column('tipo_muestra', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_unico')
    )
    op.create_table('procesamiento_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=100), nullable=True),
    sa.Column('tabla', sa.String(length=50), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('datos_nuevos', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitud_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muestra_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'INGRESADO', 'VERIFICADO', 'APROBADO', 'LIBERADO', name='estadoresultado'), nullable=True),
    sa.ForeignKeyConstraint(['muestra_id'], ['muestras.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['catalogo_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_analisis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_test_id', sa.Integer(), nullable=True),
    sa.Column('valor_resultado', sa.Float(), nullable=True),
    sa.Column('resultado_texto', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('analista_id', sa.Integer(), nullable=True),
    sa.Column('fecha_ingreso', sa.DateTime(), nullable=True),
    sa.Column('es_overrun', sa.Boolean(), nullable=True),
    sa.Column('es_critico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['analista_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['solicitud_test_id'], ['solicitud_tests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('solicitud_test_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_analisis')
    op.drop_table('solicitud_tests')
    op.drop_table('procesamiento_log')
    op.drop_table('muestras')
    op.drop_table('usuarios')
    op.drop_table('pacientes')
    op.drop_table('inventario_reactivos')
    op.drop_table('catalogo_tests')
    # ### end Alembic commands ###
